set nocompatible              "be iMproved, required
filetype off                  "required

"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

"let Vundle manage Vundle, required
"git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
Plugin 'VundleVim/Vundle.vim'

"Plugins
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'

Plugin 'Valloric/YouCompleteMe'

Plugin 'flazz/vim-colorschemes'
"Plugin 'tpope/vim-commentary'
Plugin 'scrooloose/nerdcommenter'

Plugin 'airblade/vim-gitgutter'
Plugin 'jiangmiao/auto-pairs'
Plugin 'tpope/vim-surround'
Plugin 'AndrewRadev/splitjoin.vim'
"Airline
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'

Plugin 'rking/ag.vim'

Plugin 'tpope/vim-repeat'

"Highlight
Plugin 'digitaltoad/vim-jade'


"Plugin 'tomasr/molokai'



"All of your Plugins must be added before the following line
call vundle#end()            "required
filetype plugin indent on    "required


"Plugins options
let &t_Co=256
set laststatus=2

syntax on
colorscheme jellybeans




"indent
set shiftwidth=4
set expandtab
set smarttab
set tabstop=4

"backspace
set bs=2

"search
set hlsearch

"Clear highlighting on escape in normal mode
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

"disable timeout
set ttimeoutlen=0

"line numbers
set number

"highlight chars
set listchars=tab:▸▸,trail:¬,nbsp:.,extends:❯,precedes:❮
set list

"set <leader>
let mapleader=","

"map keys
nmap ; :reg<cr>

"airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#tab_nr_type = 1

"syntactic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

"enable mouse
set mouse=a

"open vimrc
nnoremap <leader>v :e  ~/.vimrc<CR>
nnoremap <leader>V :tabnew  ~/.vimrc<CR>

"use tab to switch between open windows
nnoremap <Tab> <C-w>
nnoremap <Tab><Tab> <C-w><C-w>

"c-left/right
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

"make enter break and do newlines
nnoremap <Bslash> o<Esc>k
nnoremap <Bar> O<Esc>j

"line break
nnoremap K i<CR><Esc>

"make space in normal mode add space
nnoremap <Space> i<Space><Esc>l

":Ag on selected word
nnoremap <leader>ag :Ag <C-R><C-W><CR>

"MRU
nnoremap <C-b> :CtrlPMRU<CR>

"General file runners for various languages
function! LangRunner()
  if(&ft=="python")
    vnoremap <leader>pp :! autopep8 --max-line-length 120 -<CR>
    nnoremap <leader>pp :%! autopep8 --max-line-length 120 -<CR>
    vnoremap <leader>pi :! isort -e -<CR>
    nnoremap <leader>pi :%! isort -e -<CR>
  elseif(&ft=="ruby")
    "
  endif
endfunction

au BufEnter * call LangRunner()
